version: 2.1
defaults: &defaults
  docker:
    - image: circleci/golang:1.16
workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - build
jobs:
  test:
    !!merge <<: *defaults
    steps:
      - checkout
      - run: make test
  build:
    !!merge <<: *defaults
    steps:
      - checkout
      # Compile, and make sure it's not dynamically linked.
      - run: make bin/ssm-env && ! ldd bin/ssm-env
      - store_artifacts:
          path: bin/ssm-env
          destination: ssm-env
