version: 2

defaults: &defaults
  docker:
    - image: circleci/golang:1.16

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - build

jobs:

  test:
    << : *defaults
    steps:
      - checkout
      - run: make test

  build:
    << : *defaults
    steps:
      - checkout
      - run: make bin/ssm-env
      - store_artifacts:
          path: bin/ssm-env
          destination: ssm-env
